### ISSUE TITLE
Question: does this library support parsing DDL SQL ?

### ISSUE THREAD

**Issue by madhugilla** [JaCraig/SQLParser#3]
does this library support parsing DDL SQL ?  for example

CREATE TABLE HUB_POLICY 
(
POLICY_HK            BINARY() NOT NULL,
LOAD_TIMESTAMP       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
RECORD_SOURCE        VARCHAR(100) NULL,
POLICY_NUMBER        VARCHAR(50) NULL
);

it would be great if you could provide a sample code base for this ?

Thanks

**Comment by JaCraig** [comment]
Sorry on the delay on responding, but yeah DDL should be able to be parsed. It's literally just a wrapper around ANTLR's TSQL implementation at present. I just added a test and it can parse that no problem:

```
        [Fact]
        public void DDLParseTest()
        {
            var TestPrinter = new DDLPrinter();
            SQLParser.Parser.Parse(@"CREATE TABLE HUB_POLICY
(
POLICY_HK BINARY() NOT NULL,
LOAD_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
RECORD_SOURCE VARCHAR(100) NULL,
POLICY_NUMBER VARCHAR(50) NULL
);", TestPrinter, Enums.SQLType.TSql);
            Assert.Single(TestPrinter.SearchList);
            Assert.Equal("HUB_POLICY", TestPrinter.SearchList[0]);
        }
```

The DDLPrinter code is just this:

```
    public class DDLPrinter : TSqlParserBaseListener
    {
        public DDLPrinter()
        {
            SearchList = new List<string>();
        }

        public List<string> SearchList { get; set; }

        public override void EnterCreate_table([NotNull] TSqlParser.Create_tableContext context)
        {
            var TableName = context?.table_name().table.GetText();
            if (!string.IsNullOrEmpty(TableName))
                SearchList.Add(TableName);
            base.EnterCreate_table(context);
        }
    }
```

Basically you create a class that inherits from TSqlParserBaseListener and then override the methods that you need to read what you are looking for to build up whatever final structure you want. I literally created this because I just needed it for a specific issue of accepting select statements and figuring out the fields for display purposes. So while it's pretty feature complete on the parsing front, getting out the end result is not as nice as it could be.

Edit: Oh, and if you look in the ANTLR/TSQL directory, it has the lexer/parser used. The parser's names for each element corresponds to the methods that you override. So there is a ddl_clause method but that gets broken down into like 40 sub items, so I just implemented the create_table method instead. Line 1971 in the parser gives you the basic layout of the resulting context object in the method above. So table_name is the name, column_def_table_constraints are the constraints, etc.
